import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./header/page";
import Footer from "./footer/page";
import { AppProvider } from "../context/_app";
import { Toaster } from "react-hot-toast";
import "@uploadthing/react/styles.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className} >
        <AppProvider>
          <Toaster/>
          <main className=" max-w-4xl mx-auto p-4">
            <Header />
            {children}
            <Footer />
          </main>
        </AppProvider>
      </body>
    </html>
  );
}
